language: node_js
node_js:
- '6'
dist: trusty
sudo: false
deploy:
  provider: script
  script:
    - openssl aes-256-cbc -K $encrypted_8b6bbaa2f436_key -iv $encrypted_8b6bbaa2f436_iv -in .travis/key.enc -out .travis/deploy_key.pem -d
    - bash .travis/deploy.sh
  on:
    branch: master
